# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Shweta Ann Jacob
title: Graduate Research Assistant
email: shweta.jacob@ontariotechu.net
website: https://www.linkedin.com/in/shweta-ann-jacob/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: shhs29
linkedin_username: shweta-ann-jacob
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: SAIN Lab
#  icon: fas fa-globe
  url: https://www.sain.ca/authors/shweta-ann-jacob/
- title: Scholar Profile
#  icon: fas fa-globe
  url: https://scholar.google.ca/citations?user=OTej8BUAAAAJ&hl=en&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A second year research based Master's in Computer Science student. Current research focuses on graph neural networks and its different applications. Enthusiastic about learning new architectures and literature in the machine learning field. Previously worked in the role of a  Consultant - Application Developer in ThoughtWorks, a global technology consultancy. 3 years of experience as a full-stack developer building scalable and robust applications.

content:
  - title: Education # Title for the section
     layout: list
     content:
       - layout: left
         name: University of Ontario Institute of Technology
         dates: 2021 - 2023
         qualification: Master of Science in Computer Science
         quote: >
           Thesis-based Master's program
         description: | # this will include new lines to allow paragraphs
           - Participated in Java workshop conducted by Grey Technolabs
           - Participated in Python workshop conducted
           - Attended a Workshop on Web development held by MEC Association of Computer Students (MACS)
           - Core member of Senate (Organizing committee)

       - layout: left
         name: Govt. Model Engineering College
         dates: 2014 - 2018
         qualification: B.Tech in Computer Science and Engineering
         quote: >
           A skill oriented course where I undertook a plethora of challenging core Computer Science courses and projects
         description: | # this will include new lines to allow paragraphs
           - Participated in Java workshop conducted by Grey Technolabs
           - Participated in Python workshop conducted
           - Attended a Workshop on Web development held by MEC Association of Computer Students (MACS)
           - Core member of Senate (Organizing committee)

  - title: Research Experience # Title for the section
      layout: list
      content:
        - layout: left
          company: University of Ontario Institute of Technology
          link: https://ontariotechu.ca/
          job_title: Graduate Research Assistant
          dates: September 2021 - Present
          quote: >
            Public Research University
          description: | # this will include new lines to allow paragraphs
            - Working at SAIN lab under the supervision of Dr. Amirali Salehi-Abari on Graph Neural Networks.
            - Worked on a research paper ``Sampling Enclosing Subgraphs for Link Prediction" with my supervisor and peers which was accepted in CIKM'22 short paper research track with an acceptance rate of 29.03%.
            - Organizing, leading and attending weekly reading groups that discuss the latest literature in graph neural networks.
            - Writing literature reports of relevant research papers.
            - Guided undergraduate students in the lab server setup and maintenance process.
            - Received FBIT Student Research-Enhancement Travel Fund and SIGWeb Travel Grant to attend CIKM'22.
  - title: Industry Experience # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: left
          company: ThoughtWorks
          link: https://www.thoughtworks.com/
          job_title: Application Developer
          dates: August 2018 - July 2021
          quote: >
            A Global Software Consultancy
          description: | # this will include new lines to allow paragraphs
            - Working in an agile framework.
            - Building applications using test-driven development.
            - Building Restful APIs in Java using Springboot.
            - Working on client-side programming.
            - Implementing state management in applications.
            - Building web applications end-to-end using microservices architecture.
            - Setting deployment pipelines.
            - Building prototypes.
            - Mentoring interns and new graduates within the organization.
            - Receiving and giving feedback.
            - Helping in recruiting new talent to the organization.

        - layout: left
          company: UST Global
          link: https://www.ust-global.com/
          job_title: Intern
          dates: June 2017 - July 2017
          quote: >
            UST Global is a multinational provider IT services and solutions.
          description: | # this will include new lines to allow paragraphs
            - Learnt how blockchain can be used to solve logistics - truck route optimization problem.
            - Familiarised with how to train a bot using wit.ai.
            - Proposed an area of development using Bot to Bot communication and recommender systems.

        - layout: left
          company: Gas Turbine Research Establishment, DRDO
          link: https://www.drdo.gov.in/home
          job_title: Intern
          dates: May 2017 - June 2017
          quote: >
            The Defence Research and Development Organisation is an agency of the Government of India, charged with the military's research and development.
          description: | # this will include new lines to allow paragraphs
            - Automatic Software Change Request Generation - Developed a software to generate a formal Software Change Request which is used to initiate changes in constants, control schedules and control laws in other softwares.


  - title: Teaching Experience # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: left
          company: University of Ontario Institute of Technology
          link: https://ontariotechu.ca/
          job_title: Teaching Assistant
          dates: September 2021 - Present
          quote: >
            Public Research University
          description: | # this will include new lines to allow paragraphs
            - Fall 2022 - BUSI 1916U Business Math II
            - Fall 2022 - INFR 1010U Discrete Mathematics
            - Summer 2022 - INFR 1010U Discrete Mathematics
            - Winter 2022 - INFR 1016U Introductory Calculus
            - Fall 2021 - INFR 1010U Discrete Mathematics
            - Conducting tutorials, grading quizzes, tests and assignments and holding student hours for classes with upto 120+ students.
  - title: Skills # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: top-middle
          title: Super awesome project
          link: github.com/sproogen
          # link_text: Project Website
          additional_links:
            - title: sproogen/modern-resume-theme
              icon: fab fa-github
              url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          quote: >
            This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
          description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Workshops/Conferences Attended # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: top-middle
          title: Super awesome project
          link: github.com/sproogen
          # link_text: Project Website
          additional_links:
            - title: sproogen/modern-resume-theme
              icon: fab fa-github
              url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          quote: >
            This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
          description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Achievements and Extracurricular Accolades # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: top-middle
          title: Super awesome project
          link: github.com/sproogen
          # link_text: Project Website
          additional_links:
            - title: sproogen/modern-resume-theme
              icon: fab fa-github
              url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          quote: >
            This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
          description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Languages # Title for the section
      layout: list # Type of content section (list/text)
      content:
        - layout: top-middle
          title: Super awesome project
          link: github.com/sproogen
          # link_text: Project Website
          additional_links:
            - title: sproogen/modern-resume-theme
              icon: fab fa-github
              url: github.com/sproogen/modern-resume-theme
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
          quote: >
            This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
          description: | # this will include new lines to allow paragraphs
            I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
